# Generated by Django 3.2 on 2021-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwertyprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwertyprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
